require("config.lsp.json-lang")
require("config.lsp.lua-lang")
require("config.lsp.markdown-lang")
require("config.lsp.obsidian-app")
require("config.lsp.rust-lang")
require("config.lsp.typescript-lang")
require("config.lsp.yaml-lang")
