"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "white"
style = "plain"
template = "{{.Icon}} "
type = "os"

[[blocks.segments]]
foreground = "green"
style = "plain"
type = "path"
template = " {{ .Path }}/ "

[blocks.segments.properties]
home_icon = " "
folder_icon = " "
style = "full"

[[blocks.segments]]
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}",
  "{{ if gt .Ahead 0 }}cyan{{ end }}",
  "{{ if gt .Behind 0 }}cyan{{ end }}",
]
foreground = "green"
style = "plain"
template = """ \
{{ .HEAD }}\
{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} \
"""
type = "git"

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
branch_icon = " "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}green{{ end }}",
]
style = "plain"
template = "❯"
type = "text"

[[blocks]]
overflow = "hidden"
type = "rprompt"

[[blocks.segments]]
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}yellow{{ end }}",
]
foreground = "yellow"
style = "plain"
template = "{{ .FormattedMs }}"
type = "executiontime"

[blocks.segments.properties]
threshold = 1000

[transient_prompt]
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}green{{ end }}",
]
style = "plain"
template = "❯ "
type = "text"

[secondary_prompt]
foreground = "green"
template = "❯❯ "
