"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
background = "transparent"
foreground = "white"
style = "powerline"
template = " {{.Icon}} "
type = "os"

[[blocks.segments]]
background = "blue"
foreground = "transparent"
powerline_symbol = ""
style = "powerline"
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
background = "green"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}",
  "{{ if gt .Ahead 0 }}magenta{{ end }}",
  "{{ if gt .Behind 0 }}magenta{{ end }}",
]
foreground = "transparent"
powerline_symbol = ""
style = "powerline"
template = """ \
{{ .HEAD }}\
{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} \
"""
type = "git"

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
branch_icon = " "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
background = "transparent"
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}green{{ end }}",
]
style = "plain"
template = "❯ "
type = "text"

[[blocks]]
overflow = "hidden"
type = "rprompt"
newline = true

[[blocks.segments]]
background = "transparent"
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}white{{ end }}",
]
style = "text"
template = "{{ .FormattedMs }}"
type = "executiontime"

[transient_prompt]
background = "transparent"
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}green{{ end }}",
]
style = "plain"
template = "❯  "
type = "text"
