"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
background = "#272e33"
foreground = "white"
style = "powerline"
template = " {{.Icon}} "
type = "os"

[[blocks.segments]]
background = "blue"
foreground = "#272e33"
powerline_symbol = ""
style = "powerline"
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
background = "green"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}",
  "{{ if gt .Ahead 0 }}magenta{{ end }}",
  "{{ if gt .Behind 0 }}magenta{{ end }}",
]
foreground = "#272e33"
powerline_symbol = ""
style = "powerline"
template = """ \
{{ .HEAD }}\
{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} \
"""
type = "git"

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
branch_icon = " "
